{
  "hash": "3020a315ef988994cbf3f87536729cf6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"3. Instrumental Variables\"\nexecute:\n  warning: false\n  message: false\n---\n\n![](../images/ch03_visual_summary.svg)\n\n<div class=\"chapter-resources\">\n<a href=\"#\" class=\"resource-btn\">AI Slides</a>\n<a href=\"#\" class=\"resource-btn\">Quiz</a>\n<a href=\"#\" class=\"resource-btn\">AI Tutor</a>\n</div>\n\n::: {.callout-tip}\n## Learning Objectives\n\nBy the end of this chapter, you will be able to:\n\n- Explain why **non-compliance** in experiments creates a gap between assigned and received treatment\n- Define the **Local Average Treatment Effect (LATE)** and the IV formula: LATE = reduced form / first stage\n- Classify subjects into **complier types**: never-takers, compliers, always-takers, and defiers\n- Understand the three requirements for a valid instrument\n- Explain how **Two-Stage Least Squares (2SLS)** implements IV in practice\n- Recognize **weak instruments** and why they matter\n:::\n\nThis chapter addresses a common real-world complication: what happens when people don't follow their assigned treatment? The solution --- instrumental variables --- turns partial compliance into a powerful tool for causal inference.\n\n```{mermaid}\n%%| label: fig-roadmap\n%%| fig-cap: \"Roadmap for Chapter 3\"\n\ngraph TD\n    A[\"THE QUESTION: What if people don't comply with their treatment assignment?\"]\n    B[\"THE COMPLIANCE PROBLEM: Assigned treatment differs from received treatment\"]\n    C[\"THE IV FRAMEWORK: Use assignment as an instrument for actual treatment\"]\n    D[\"THE CASE STUDIES: KIPP lotteries, domestic violence, family size\"]\n    E[\"THE TOOLKIT: Two-Stage Least Squares and weak instrument diagnostics\"]\n\n    A --> B --> C --> D --> E\n\n    style A fill:#3498db,color:#fff\n    style B fill:#e67e22,color:#fff\n    style C fill:#c0392b,color:#fff\n    style D fill:#8e44ad,color:#fff\n    style E fill:#2d8659,color:#fff\n```\n\n\n# When Experiments Break Down\n\nRandomized experiments are the gold standard for causal inference (Chapter 1). But in practice, experiments rarely go exactly as planned. Police officers may not follow their assigned protocol. Patients may not take their assigned medication. Lottery winners may not enroll in the program they won.\n\nWhen the treatment people **receive** differs from the treatment they were **assigned**, we face the problem of **non-compliance**. Simply comparing outcomes by *received* treatment reintroduces selection bias, because the choice to comply may be related to the outcome.\n\n## The Minneapolis Domestic Violence Experiment\n\nThe **Minneapolis Domestic Violence Experiment (MDVE)** illustrates this perfectly. In the early 1980s, researchers randomly assigned police officers responding to domestic violence calls to one of three actions:\n\n- **Arrest** the suspect\n- **Advise** the couple (counseling/mediation)\n- **Separate** them (remove suspect for 8 hours)\n\nThe goal was to learn which response best prevented future violence. But police officers didn't always follow their assignment.\n\n::: {#10339220 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\n# --- Data source (GitHub URL with local fallback) ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/\"\nLOCAL_DATA_PATH = \"../../data/\"\n\ndef load_csv(path):\n    \"\"\"Load CSV from GitHub raw URL; fall back to local path if unavailable.\"\"\"\n    try:\n        return pd.read_csv(GITHUB_DATA_URL + path)\n    except Exception:\n        return pd.read_csv(LOCAL_DATA_PATH + path)\n\n# Load clean MDVE data: each row is one domestic violence case\n# 'assigned' = what police were told to do; 'delivered' = what they actually did\nmdve = load_csv(\"ch3/mdve_clean.csv\")\nmdve.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>assigned</th>\n      <th>delivered</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Separate</td>\n      <td>Separate</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Arrest</td>\n      <td>Arrest</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Arrest</td>\n      <td>Arrest</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-crosstab .cell tbl-cap='Cross-tabulation of assigned vs. delivered police response in the MDVE. Row percentages show compliance rates.' execution_count=2}\n``` {.python .cell-code}\n# Cross-tabulate: what treatment was assigned vs. what was actually delivered?\nct = pd.crosstab(mdve[\"assigned\"], mdve[\"delivered\"], margins=True, margins_name=\"Total\")\nct = ct[[\"Arrest\", \"Advise\", \"Separate\", \"Total\"]]  # reorder columns\n\n# Show counts\nct\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>delivered</th>\n      <th>Arrest</th>\n      <th>Advise</th>\n      <th>Separate</th>\n      <th>Total</th>\n    </tr>\n    <tr>\n      <th>assigned</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Advise</th>\n      <td>19</td>\n      <td>84</td>\n      <td>5</td>\n      <td>108</td>\n    </tr>\n    <tr>\n      <th>Arrest</th>\n      <td>91</td>\n      <td>0</td>\n      <td>1</td>\n      <td>92</td>\n    </tr>\n    <tr>\n      <th>Separate</th>\n      <td>26</td>\n      <td>5</td>\n      <td>83</td>\n      <td>114</td>\n    </tr>\n    <tr>\n      <th>Total</th>\n      <td>136</td>\n      <td>89</td>\n      <td>89</td>\n      <td>314</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-compliance .cell tbl-cap='Compliance rates by assignment group. Officers almost always followed arrest orders but frequently deviated from advise/separate assignments.' execution_count=3}\n``` {.python .cell-code}\n# Compute compliance rate for each assignment group\nrows = []\nfor group in [\"Arrest\", \"Advise\", \"Separate\"]:\n    group_data = mdve[mdve[\"assigned\"] == group]\n    complied = (group_data[\"delivered\"] == group).sum()\n    rows.append({\n        \"Assigned\": group,\n        \"N\": len(group_data),\n        \"Complied\": complied,\n        \"Compliance Rate\": f\"{complied / len(group_data):.1%}\",\n    })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Assigned</th>\n      <th>N</th>\n      <th>Complied</th>\n      <th>Compliance Rate</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Arrest</td>\n      <td>92</td>\n      <td>91</td>\n      <td>98.9%</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Advise</td>\n      <td>108</td>\n      <td>84</td>\n      <td>77.8%</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Separate</td>\n      <td>114</td>\n      <td>83</td>\n      <td>72.8%</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-warning}\n## Asymmetric compliance\n\nOfficers followed arrest orders **99% of the time** but deviated from advise and separate assignments much more often (78% and 73%). When they deviated, they almost always chose to arrest instead --- likely because the suspect was particularly aggressive. This means the group that *actually received* arrest includes both randomly assigned arrests and the most dangerous cases from other assignments. Comparing outcomes by delivered treatment would be biased.\n:::\n\n::: {.callout-note}\n## Intuition Builder: IV as a Chain Reaction\n\nThink of IV as tracing a chain of dominoes:\n\n- **Domino 1 (Instrument → Treatment)**: The random assignment form *nudges* the police officer's action. This is the **first stage**.\n- **Domino 2 (Treatment → Outcome)**: The police action *affects* future violence. This is the **causal effect** we want.\n- **What we observe**: The assignment form's effect on future violence — the **reduced form** (Domino 1 × Domino 2).\n- **The IV trick**: Divide the reduced form by the first stage to isolate Domino 2 alone.\n\nThe instrument must push the first domino (relevance) and must *only* work through the chain (exclusion restriction). If the instrument directly tips the last domino without going through treatment, the chain is broken.\n:::\n\n\n# The IV Framework\n\n## The Core Idea\n\nInstrumental variables solves the compliance problem by using the **random assignment** (the instrument) instead of the actual treatment to estimate causal effects. The logic is a chain reaction:\n\n```{mermaid}\n%%| label: fig-iv-chain\n%%| fig-cap: \"The IV chain reaction: the instrument affects the outcome only through its effect on treatment.\"\n\ngraph LR\n    Z[\"Instrument (Z): Random assignment\"]\n    D[\"Treatment (D): Actual police action\"]\n    Y[\"Outcome (Y): Future violence\"]\n\n    Z -->|\"First stage\"| D\n    D -->|\"Causal effect\"| Y\n    Z -.->|\"Reduced form\"| Y\n\n    style Z fill:#8e44ad,color:#fff\n    style D fill:#3498db,color:#fff\n    style Y fill:#2d8659,color:#fff\n```\n\nThe **LATE (Local Average Treatment Effect)** combines these two pieces:\n\n$$\\lambda_{LATE} = \\frac{\\rho}{\\phi} = \\frac{\\text{Reduced form (effect of } Z \\text{ on } Y)}{\\text{First stage (effect of } Z \\text{ on } D)}$$\n\nwhere $\\rho$ (rho) is the reduced-form effect of the instrument on the outcome, and $\\phi$ (phi) is the first-stage effect of the instrument on the treatment.\n\n## Three Requirements for a Valid Instrument\n\n1. **Relevance**: The instrument must affect the treatment. In the MDVE, random assignment must actually change what police do (first stage $\\neq$ 0).\n\n2. **Independence**: The instrument must be randomly assigned (or \"as good as random\"). The MDVE's randomization satisfies this.\n\n3. **Exclusion restriction**: The instrument affects the outcome **only through** the treatment. The random assignment shouldn't directly affect recidivism except through the police action taken.\n\n## Applying the IV Formula to the MDVE\n\nLet's compute the IV estimate step by step using the MDVE data. We simplify to a binary comparison: **arrest** ($Z = 0$) vs. **coddle** (advise or separate, $Z = 1$).\n\n::: {#tbl-iv-recipe .cell tbl-cap='The IV recipe applied to the MDVE: reduced form divided by first stage gives the LATE.' execution_count=4}\n``` {.python .cell-code}\n# Create binary variables for the IV calculation\n# Z = instrument: assigned to coddle (advise or separate) vs. arrest\nmdve[\"z_coddle\"] = (mdve[\"assigned\"] != \"Arrest\").astype(int)\n\n# D = treatment: actually coddled (advise or separate) vs. arrested\nmdve[\"d_coddle\"] = (mdve[\"delivered\"] != \"Arrest\").astype(int)\n\n# Step 1: FIRST STAGE — does assignment affect actual treatment?\n# Fraction coddled when assigned to coddle vs. assigned to arrest\nfs_coddle = mdve.loc[mdve[\"z_coddle\"] == 1, \"d_coddle\"].mean()\nfs_arrest = mdve.loc[mdve[\"z_coddle\"] == 0, \"d_coddle\"].mean()\nfirst_stage = fs_coddle - fs_arrest\n\n# Step 2: REDUCED FORM — does assignment affect recidivism?\n# (We don't have recidivism in this clean dataset, so we use published numbers)\nreduced_form = 0.211 - 0.097  # from the original study\n\n# Step 3: LATE = reduced form / first stage\nlate = reduced_form / first_stage\n\npd.DataFrame({\n    \"Step\": [\"First stage (coddled if assigned coddle)\", \"First stage (coddled if assigned arrest)\",\n             \"First stage (difference)\", \"Reduced form (recidivism difference)\", \"LATE = RF / FS\"],\n    \"Value\": [f\"{fs_coddle:.3f}\", f\"{fs_arrest:.3f}\", f\"{first_stage:.3f}\",\n              f\"{reduced_form:.3f}\", f\"{late:.3f}\"],\n})\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Step</th>\n      <th>Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>First stage (coddled if assigned coddle)</td>\n      <td>0.797</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>First stage (coddled if assigned arrest)</td>\n      <td>0.011</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>First stage (difference)</td>\n      <td>0.786</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Reduced form (recidivism difference)</td>\n      <td>0.114</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>LATE = RF / FS</td>\n      <td>0.145</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-important}\n## Key finding\n\nCoddling (advise/separate) **increases recidivism by 14.5 percentage points** among compliers --- those officers who followed their assignment. This is much larger than the naive comparison of delivered treatments (8.7 pp) would suggest, because the naive estimate is contaminated by selection bias.\n:::\n\n::: {.callout-warning}\n## Common Misconception: LATE is not the Average Treatment Effect\n\nThe IV estimate of 14.5 pp applies **only to compliers** --- officers who followed whatever their assignment form said. It tells us nothing about:\n\n- **Always-takers** (officers who always arrest, regardless of assignment) --- they may be more experienced and arrest more effectively\n- **Never-takers** (hypothetical officers who never arrest) --- they don't exist in this data\n\nDifferent instruments identify effects for *different subpopulations*. A KIPP lottery identifies effects for families who participate in the lottery; a twin birth identifies effects for families on the margin of having another child. The \"L\" in LATE stands for \"local\" --- local to the population whose behavior is changed by the instrument.\n:::\n\n\n# The Four Types of Subjects\n\nIn any IV setting, subjects fall into four categories based on how they would respond to the instrument:\n\n| Type | Behavior | Role in IV |\n|:---|:---|:---|\n| **Complier** | Does what they're told — treatment follows assignment | The population LATE estimates effects for |\n| **Always-taker** | Always gets treatment regardless of assignment | Unaffected by instrument; IV is silent |\n| **Never-taker** | Never gets treatment regardless of assignment | Unaffected by instrument; IV is silent |\n| **Defier** | Does the opposite of assignment | Assumed not to exist (monotonicity) |\n\n: The four complier types in an IV framework {.striped}\n\n::: {.callout-note}\n## LATE is the effect for compliers only\n\nThe IV estimate tells us the causal effect **specifically for compliers** --- people whose treatment was determined by the instrument. It does not necessarily apply to always-takers or never-takers. In the MDVE, compliers are officers who followed whatever assignment they received. The LATE tells us what happens when *these particular officers* arrest vs. coddle.\n:::\n\n\n# Case Study: KIPP Charter School Lotteries\n\nThe **Knowledge Is Power Program (KIPP)** is a network of charter schools with extended school days and a \"no excuses\" discipline culture. KIPP Lynn in Massachusetts became oversubscribed after 2005, so admission was decided by lottery --- creating a natural instrument.\n\n**The IV components:**\n\n- **Instrument ($Z$)**: Winning the KIPP lottery\n- **Treatment ($D$)**: Actually attending KIPP\n- **Outcome ($Y$)**: Math test scores\n\n**Results:**\n\n| Component | Estimate |\n|:---|:---|\n| First stage (lottery → attendance) | 0.741 (74.1% of winners attended) |\n| Reduced form (lottery → math scores) | +0.355 standard deviations |\n| **LATE** (attendance → math scores) | **+0.48 standard deviations** |\n\n: IV estimates of KIPP attendance effects on math scores {.striped}\n\nA half standard deviation improvement in math in one year is a remarkable effect. Balance checks confirmed that lottery winners and losers looked similar at baseline, supporting the validity of the instrument.\n\nThis lottery-based evidence has been influential in education policy. Charter school supporters cite KIPP's results as proof that intensive, structured programs can close achievement gaps for disadvantaged students. Critics note that LATE applies only to lottery compliers (motivated families who applied), and the effect might not generalize to all students.\n\n\n# Case Study: Does Family Size Reduce Children's Education?\n\nThe quantity-quality tradeoff hypothesis suggests that larger families dilute parental investment, reducing each child's education. The naive correlation supports this: children with more siblings get less schooling (-0.15 years per sibling in OLS).\n\nBut is this causal? Less-educated parents tend to have more children *and* less-educated children. Two clever instruments address this:\n\n**Twin births**: When a second birth produces twins instead of a singleton, family size increases by one --- essentially at random. First stage: +0.32 children.\n\n**Sibling sex composition**: Parents with same-sex first two children are more likely to have a third (seeking gender balance). First stage: +0.08 children.\n\n**Results**: Both instruments show a reduced form of approximately **zero** --- no effect of family size on children's education. The 2SLS estimate using both instruments is +0.24 (SE: 0.13), completely reversing the negative OLS estimate.\n\n::: {.callout-important}\n## Selection bias explains the naive correlation\n\nThe strong negative OLS relationship between family size and education appears to be entirely driven by selection bias. When we use instruments that generate exogenous variation in family size, the effect vanishes. Less-educated parents have more children AND less-educated children --- but one does not cause the other.\n:::\n\nThis finding has major **policy implications**. For decades, governments promoted smaller families based on the belief that fewer children means more investment per child (the \"quantity-quality tradeoff\"). China's one-child policy and India's forced sterilization programs were partly justified by this logic. The IV evidence suggests the tradeoff is much weaker than previously thought --- the naive correlation was driven by confounders, not causation.\n\n\n## When to Use IV vs. Other Methods\n\n| Feature | RCT (Chapter 1) | OLS with Controls | IV / 2SLS (This Chapter) |\n|:---|:---|:---|:---|\n| **Requires** | Random assignment of treatment | Observable confounders only | A valid instrument |\n| **Handles** | All confounders (observed + unobserved) | Only observed confounders | Unobserved confounders (via instrument) |\n| **Estimates** | ATE (average for everyone) | Conditional association | LATE (average for compliers) |\n| **Weakness** | Expensive, often impractical | Fails with unobserved confounders | Needs strong, valid instrument |\n\n: When to use which method {.striped}\n\n\n# Two-Stage Least Squares (2SLS)\n\nThe IV formula $\\lambda = \\rho / \\phi$ works for a single binary instrument. In practice, we often have multiple instruments, covariates, or non-binary treatments. **Two-Stage Least Squares** handles all of these.\n\n**Stage 1 (First Stage):** Predict treatment using the instrument(s)\n$$D_i = \\alpha_1 + \\phi Z_i + \\gamma_1 X_i + e_{1i}$$\n\n**Stage 2 (Second Stage):** Regress the outcome on the predicted treatment\n$$Y_i = \\alpha_2 + \\lambda_{2SLS} \\hat{D}_i + \\gamma_2 X_i + e_{2i}$$\n\n::: {.callout-warning}\n## Never run 2SLS by hand\n\nIf you manually run two separate regressions and use fitted values from the first in the second, you will get the right coefficient but **wrong standard errors**. Always use dedicated IV software that computes correct standard errors automatically.\n:::\n\n## 2SLS in Python\n\nIn Python, the `linearmodels` library provides `IV2SLS`. The formula syntax uses **square brackets** to indicate the endogenous variable and its instrument:\n\n```\n\"outcome ~ exogenous_controls + [endogenous_variable ~ instrument]\"\n```\n\nHere is how you would run 2SLS for the KIPP charter school example (using hypothetical data to illustrate the syntax):\n\n::: {#4760f8e9 .cell execution_count=5}\n``` {.python .cell-code}\n# Syntax demonstration (not run on real data — KIPP data is not available)\n# from linearmodels.iv import IV2SLS\n#\n# result = IV2SLS.from_formula(\n#     \"math_score ~ 1 + [attended_kipp ~ won_lottery]\",\n#     data=kipp_data,\n# ).fit(cov_type=\"robust\")\n#\n# The key parts:\n#   math_score           = outcome (Y)\n#   attended_kipp        = endogenous treatment (D) — inside [ ]\n#   won_lottery          = instrument (Z) — after the ~ inside [ ]\n#   1                    = intercept (constant)\n#   cov_type=\"robust\"    = heteroskedasticity-robust standard errors\n\nprint(\"IV2SLS syntax: 'Y ~ controls + [D ~ Z]'\")\nprint(\"  [D ~ Z] means: instrument D using Z\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIV2SLS syntax: 'Y ~ controls + [D ~ Z]'\n  [D ~ Z] means: instrument D using Z\n```\n:::\n:::\n\n\nWe will see `IV2SLS` in action with real data in Chapter 6, where we estimate the returns to schooling using quarter-of-birth instruments.\n\n\n# Weak Instruments\n\nAn instrument is **weak** when it has only a small effect on the treatment (small first stage). Weak instruments cause:\n\n- 2SLS estimates biased toward OLS\n- Misleading confidence intervals\n- Unreliable inference\n\n::: {.callout-tip}\n## The F > 10 rule of thumb\n\nTest the joint significance of instruments in the first-stage regression. If the **F-statistic is below 10**, the instruments may be too weak. When in doubt, check the reduced form --- if the instrument's direct effect on the outcome isn't visible, the IV estimate is likely unreliable.\n:::\n\n::: {.callout-warning}\n## Common Misconception: More data doesn't fix weak instruments\n\nUnlike standard estimation, where larger samples give more precise estimates, **weak-instrument bias does not vanish with more data**. Even with a million observations, if the first-stage F-statistic is below 10, the 2SLS estimate can be severely biased toward OLS. The solution is a stronger instrument, not a bigger sample.\n:::\n\n::: {.callout-note}\n## Connection to Chapters 1 and 4\n\nIV connects the methods from other chapters:\n\n- **Chapter 1 (RCTs)**: When an experiment has non-compliance (some people don't take their assigned treatment), the random assignment serves as an instrument. The ITT (intent-to-treat) effect is the reduced form; dividing by the compliance rate gives the LATE.\n- **Chapter 4 (RD)**: A **fuzzy RD** is an IV problem where the cutoff dummy serves as the instrument. The first stage is the jump in treatment probability at the cutoff; the reduced form is the jump in outcomes. LATE = reduced form / first stage.\n:::\n\n\n# Historical Perspective: Philip Wright\n\nThe identification problem --- how to separate supply from demand when both are determined simultaneously --- was solved by **Philip G. Wright** in 1928. In an appendix to his book on tariffs, Wright introduced \"external factors\" (what we now call instruments) that shift one curve without affecting the other.\n\nWright's innovation lay dormant for decades before being rediscovered. His son **Sewall Wright**, a geneticist, contributed the mathematical framework of path analysis. Together, they pioneered the idea that researchers must find sources of variation that affect one part of a system without directly affecting the outcome of interest.\n\n\n# Key Takeaways\n\n```{mermaid}\n%%| label: fig-concept-map\n%%| fig-cap: \"How the key concepts of Chapter 3 connect\"\n\ngraph TD\n    Q[\"Non-compliance in experiments\"]\n    Z[\"Instrument: random assignment\"]\n    FS[\"First stage: does Z affect D?\"]\n    RF[\"Reduced form: does Z affect Y?\"]\n    LATE[\"LATE = reduced form / first stage\"]\n    CT[\"Complier types determine who LATE applies to\"]\n    TSLS[\"Two-Stage Least Squares: practical implementation\"]\n\n    Q --> Z --> FS\n    Z --> RF\n    FS --> LATE\n    RF --> LATE\n    LATE --> CT\n    LATE --> TSLS\n\n    style Q fill:#c0392b,color:#fff\n    style Z fill:#8e44ad,color:#fff\n    style LATE fill:#2d8659,color:#fff\n    style TSLS fill:#3498db,color:#fff\n```\n\n1. **Non-compliance** is common in experiments. Comparing outcomes by *received* treatment reintroduces selection bias.\n\n2. **Instrumental variables** uses random assignment as an instrument to recover causal effects despite non-compliance.\n\n3. **LATE = reduced form / first stage** --- the ratio of the instrument's effect on the outcome to its effect on treatment.\n\n4. **LATE applies to compliers only** --- the subpopulation whose treatment was actually changed by the instrument.\n\n5. **Three requirements**: relevance (first stage), independence (random assignment), and exclusion restriction (single channel).\n\n6. **2SLS** is the practical implementation. Always use dedicated software for correct standard errors.\n\n7. **Weak instruments** (F < 10) produce unreliable estimates. Always check the first stage.\n\n\n# Exercises\n\n## Conceptual Questions\n\n::: {.callout-caution}\n## Conceptual Questions\n\n1. **Classifying complier types**: In a medical trial, patients are randomly assigned to receive a new drug or placebo, but some placebo patients obtain the drug on their own, and some drug patients refuse to take it. (a) Who are the always-takers? (b) Who are the compliers? (c) If 80% of the drug group takes the drug and 10% of the placebo group obtains it, what is the first stage?\n\n2. **Computing LATE**: Using the MDVE numbers: first stage = 0.786, reduced form = 0.114. (a) Compute the LATE. (b) Why is this larger than the naive comparison of delivered treatments (0.087)? (c) What does \"selection into treatment\" mean in this context?\n\n3. **Exclusion restriction**: A researcher uses rainfall as an instrument for agricultural output to estimate the effect of output on conflict. What could violate the exclusion restriction?\n\n4. **Why LATE is local**: Using the MDVE context, explain why the IV estimate applies only to compliers. What can we say (or not say) about the effect of arrest on always-takers --- those suspects who would be arrested regardless of what the assignment form said?\n\n5. **Monotonicity**: The IV framework assumes there are no \"defiers\" (people who do the opposite of their assignment). In the MDVE, a defier would be an officer who arrests when told to coddle and coddles when told to arrest. Why is this assumption reasonable in the MDVE context? Can you think of a setting where it might fail?\n:::\n\n## Research Tasks\n\n::: {.callout-caution}\n## Research Tasks\n\n1. **Compliance by assignment group**: Using `mdve_clean.csv`, compute the compliance rate separately for each of the three assignment groups (Arrest, Advise, Separate). Which group has the highest compliance? What does this asymmetry suggest about how police exercise discretion?\n\n2. **Binary vs. multi-category first stage**: Using `mdve_clean.csv`, compute the first stage two ways: (a) using the binary \"arrest vs. coddle\" indicator, and (b) using all three assignment categories in a cross-tabulation. Compare the results and explain which approach is simpler for an IV analysis.\n\n3. **Cross-over patterns**: Using `mdve_clean.csv`, among officers who deviated from their assignment, which direction did they most commonly cross over (e.g., from advise to arrest, or from separate to arrest)? What does this pattern suggest about officer behavior?\n:::\n\n\n# Solutions\n\n## Conceptual Questions\n\n**Q1.** (a) Always-takers are patients who take the drug regardless of assignment --- those in the placebo group who obtain it on their own. (b) Compliers are patients who follow their assignment: they take the drug when assigned to drug, and don't take it when assigned to placebo. (c) The first stage is: $P(\\text{take drug} | \\text{assigned drug}) - P(\\text{take drug} | \\text{assigned placebo}) = 0.80 - 0.10 = 0.70$.\n\n**Q2.** (a) LATE = 0.114 / 0.786 = 0.145 (14.5 percentage points). (b) The naive comparison (0.087) is smaller because it is contaminated by selection bias: officers who deviated from their \"coddle\" assignment to arrest instead were responding to more violent suspects. These suspects would have reoffended at higher rates regardless. The naive estimate mixes the causal effect with this selection. (c) \"Selection into treatment\" means that the officers who chose to arrest (despite being told to coddle) were systematically selecting the most dangerous cases, making the arrested group look worse than it would under random assignment.\n\n**Q3.** Rainfall could affect conflict through channels other than agricultural output. For example: (a) heavy rain may flood roads and prevent armed groups from mobilizing, reducing conflict directly; (b) drought may force migration, creating social tensions unrelated to agricultural output; (c) rainfall affects water availability for drinking and sanitation, which could spark resource conflicts. Any of these channels would violate the exclusion restriction because rainfall would affect conflict independently of its effect on agricultural output.\n\n**Q4.** The IV estimate is a Local Average Treatment Effect --- it applies specifically to compliers, whose treatment was changed by the instrument. In the MDVE, compliers are officers who followed their random assignment. For always-takers (officers who arrested regardless of what the form said), the instrument didn't change their behavior, so IV cannot tell us anything about the treatment effect for them. Always-takers may respond differently to arrest --- perhaps they are more experienced officers who arrest only when necessary, making arrest more effective for their cases. But IV is silent on this.\n\n## Research Tasks\n\n**R1.**\n\n::: {#tbl-sol-compliance .cell tbl-cap='Compliance rates by assignment group' execution_count=6}\n``` {.python .cell-code}\nimport pandas as pd\n\nmdve = load_csv(\"ch3/mdve_clean.csv\")\n\n# Compute compliance rate: fraction who received their assigned treatment\nrows = []\nfor group in [\"Arrest\", \"Advise\", \"Separate\"]:\n    group_data = mdve[mdve[\"assigned\"] == group]\n    complied = (group_data[\"delivered\"] == group).sum()\n    rows.append({\n        \"Assigned\": group,\n        \"N\": len(group_data),\n        \"Complied\": complied,\n        \"Compliance rate\": f\"{complied / len(group_data):.1%}\",\n    })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Assigned</th>\n      <th>N</th>\n      <th>Complied</th>\n      <th>Compliance rate</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Arrest</td>\n      <td>92</td>\n      <td>91</td>\n      <td>98.9%</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Advise</td>\n      <td>108</td>\n      <td>84</td>\n      <td>77.8%</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Separate</td>\n      <td>114</td>\n      <td>83</td>\n      <td>72.8%</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nArrest has the highest compliance (99%). Officers almost always arrest when told to, but frequently deviate from advise (78%) and separate (73%) assignments --- usually by arresting instead. This suggests officers exercise discretion toward arrest when they perceive danger, which is why comparing by *delivered* treatment introduces selection bias.\n\n**R2.**\n\n::: {#tbl-sol-firststage .cell tbl-cap='First stage: binary vs. multi-category' execution_count=7}\n``` {.python .cell-code}\n# Binary approach: arrest (Z=0) vs. coddle (Z=1)\nmdve[\"z_coddle\"] = (mdve[\"assigned\"] != \"Arrest\").astype(int)\nmdve[\"d_coddle\"] = (mdve[\"delivered\"] != \"Arrest\").astype(int)\n\nfs_binary = mdve.groupby(\"z_coddle\")[\"d_coddle\"].mean()\nprint(\"Binary first stage:\")\nprint(f\"  P(coddled | assigned coddle) = {fs_binary[1]:.3f}\")\nprint(f\"  P(coddled | assigned arrest) = {fs_binary[0]:.3f}\")\nprint(f\"  Difference = {fs_binary[1] - fs_binary[0]:.3f}\")\n\n# Multi-category: full cross-tabulation\nprint(\"\\nFull cross-tabulation:\")\nct = pd.crosstab(mdve[\"assigned\"], mdve[\"delivered\"], normalize=\"index\").round(3)\nct\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBinary first stage:\n  P(coddled | assigned coddle) = 0.797\n  P(coddled | assigned arrest) = 0.011\n  Difference = 0.786\n\nFull cross-tabulation:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>delivered</th>\n      <th>Advise</th>\n      <th>Arrest</th>\n      <th>Separate</th>\n    </tr>\n    <tr>\n      <th>assigned</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Advise</th>\n      <td>0.778</td>\n      <td>0.176</td>\n      <td>0.046</td>\n    </tr>\n    <tr>\n      <th>Arrest</th>\n      <td>0.000</td>\n      <td>0.989</td>\n      <td>0.011</td>\n    </tr>\n    <tr>\n      <th>Separate</th>\n      <td>0.044</td>\n      <td>0.228</td>\n      <td>0.728</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe binary approach gives a clean first stage of ~0.786. The multi-category cross-tab provides more detail but is harder to use in a standard IV framework because IV requires a single treatment variable. The binary simplification (arrest vs. everything else) is standard practice when the research question is \"does arrest reduce recidivism compared to alternative responses.\"\n\n**Q5.** In the MDVE, monotonicity is reasonable: it's hard to imagine an officer who would arrest when told to coddle but coddle when told to arrest. Officers deviate *toward* arrest (the more cautious action), not away from it. Monotonicity might fail in settings where the instrument triggers opposite reactions in different subgroups --- for example, a mandatory tutoring assignment where some students rebel against being told to attend (defiers who skip when assigned) but voluntarily attend when not assigned.\n\n**R3.**\n\n::: {#tbl-sol-crossover .cell tbl-cap='Cross-over patterns: where do deviating officers go?' execution_count=8}\n``` {.python .cell-code}\n# Among cases where assignment != delivery, what are the patterns?\ndeviators = mdve[mdve[\"assigned\"] != mdve[\"delivered\"]]\n\ncrossover = pd.crosstab(deviators[\"assigned\"], deviators[\"delivered\"])\ncrossover\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>delivered</th>\n      <th>Advise</th>\n      <th>Arrest</th>\n      <th>Separate</th>\n    </tr>\n    <tr>\n      <th>assigned</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Advise</th>\n      <td>0</td>\n      <td>19</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>Arrest</th>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>Separate</th>\n      <td>5</td>\n      <td>26</td>\n      <td>0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe dominant pattern is cross-over from advise or separate **toward arrest**. Very few officers cross from arrest to another action. This asymmetry reflects officers exercising discretion toward the more protective response when they perceive the situation as dangerous --- exactly the selection bias that makes naive comparisons misleading.\n\n",
    "supporting": [
      "03-instrumental-variables_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}