{
  "hash": "c5832c22951520c4aa95f2b4e61033ae",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"5. Differences-in-Differences\"\nexecute:\n  warning: false\n  message: false\n---\n\n![](../images/ch05_visual_summary.svg)\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/cmg777/intro2causal/blob/main/notebooks_colab/05-differences-in-differences.ipynb)\n\n\n::: {.callout-tip}\n### Learning Objectives\n\nBy the end of this chapter, you will be able to:\n\n- Explain the **difference-in-differences (DD)** strategy for causal inference\n- Construct a **counterfactual** using a control group's trajectory\n- State and assess the **parallel trends assumption**\n- Estimate DD effects using **regression with fixed effects**\n- Understand why **state-specific trends**, **weighting**, and **clustered standard errors** matter\n- Interpret DD results from two case studies: banking crises and drinking age policy\n:::\n\nThis chapter introduces a method for settings where treatment is not randomly assigned but varies across groups and over time. By comparing *changes* rather than levels, DD removes time-invariant confounders.\n\n```{mermaid}\n%%| label: fig-roadmap\n%%| fig-cap: \"Roadmap for Chapter 5\"\n\ngraph TD\n    A[\"THE QUESTION: Did Fed intervention save banks during the Great Depression?\"]\n    B[\"THE INSIGHT: Compare changes in treated vs. control groups over time\"]\n    C[\"THE ASSUMPTION: Without treatment, both groups would have followed parallel trends\"]\n    D[\"THE TOOL: Regression with state and year fixed effects\"]\n    E[\"THE EVIDENCE: Banking crises and drinking age mortality\"]\n\n    A --> B --> C --> D --> E\n\n    style A fill:#3498db,color:#fff\n    style B fill:#e67e22,color:#fff\n    style C fill:#c0392b,color:#fff\n    style D fill:#8e44ad,color:#fff\n    style E fill:#2d8659,color:#fff\n    linkStyle default stroke:#64748b,stroke-width:2px\n```\n\n\n## Key Concepts and Definitions\n\n**Difference-in-Differences (DD):** A causal inference method that compares the change in outcomes over time for a treated group to the change for an untreated control group. By differencing twice --- across groups and across time --- DD removes both fixed group differences and common time trends.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nComparing the change in bank survival in the 6th Fed District (intervention) to the change in the 8th District (no intervention) during the Great Depression isolates the causal effect of Fed policy.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike a diet experiment where you and your friend both weigh yourselves before and after the holidays. You dieted; your friend did not. The difference in your weight changes (not your weight levels) reveals whether the diet worked.\n:::\n::::\n:::::\n\n**Parallel Trends Assumption:** The critical identifying assumption of DD: in the absence of treatment, the treated and control groups would have followed the same trajectory over time. Groups can start at different levels, but their changes must be similar.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nThe assumption requires that, without the Fed's intervention, the 6th District would have lost banks at the same rate as the 8th District.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike two runners on parallel tracks. They can start at different positions, but without any intervention, they would run at the same pace. If one suddenly speeds up, the intervention (treatment) must have caused it.\n:::\n::::\n:::::\n\n**Counterfactual:** The unobserved outcome that would have occurred in the absence of treatment. In DD, the control group's trajectory is used to construct the counterfactual for the treated group.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nThe dashed line in the Mississippi banking chart shows how many banks the 6th District would have had if it had followed the 8th District's decline --- that is the counterfactual.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike an alternate timeline in a movie. You cannot observe what would have happened if the hero had made a different choice, but you can estimate it using information from other characters who faced similar circumstances.\n:::\n::::\n:::::\n\n**Treatment Group vs. Control Group:** The treatment group receives the intervention; the control group does not. In DD, the control group provides the benchmark trajectory that estimates what would have happened to the treated group without the intervention.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nIn the MLDA DD, states that lowered their drinking age are the treatment group; states that did not change their laws are the control group.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike a science fair project where one plant gets fertilizer (treatment) and another identical plant does not (control). The control plant shows what growth looks like without the fertilizer.\n:::\n::::\n:::::\n\n**Before-After Comparison:** A simple comparison of outcomes before and after a treatment within the same group. Alone, it is vulnerable to confounding by time trends; DD improves on it by subtracting the control group's change.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nComparing bank counts in the 6th District in 1930 vs. 1933 shows a decline, but some decline was caused by the Depression, not the policy. The before-after comparison alone cannot separate the two.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike noticing you feel better after taking medicine during flu season. You might have recovered naturally --- the improvement could be the passage of time, not the pill. You need a comparison group to tell.\n:::\n::::\n:::::\n\n**Fixed Effects:** Variables included in a regression to absorb all time-invariant differences between groups (group fixed effects) or all group-invariant differences across time periods (time fixed effects).\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nState fixed effects remove permanent differences between states (culture, geography). Year fixed effects remove nationwide trends (improvements in vehicle safety).\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike adjusting for the home-court advantage in sports. Some teams always play better at home (group fixed effect); some seasons are more competitive overall (time fixed effect). Fixed effects remove these constant factors so you can see the effect of a specific coaching change.\n:::\n::::\n:::::\n\n**State-Specific Trends:** An extension of the DD model that allows each state (or group) to follow its own linear time trend, rather than assuming all groups share the same trend. This is a more demanding test of the DD estimate.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nSome states may have had declining death rates even before changing their drinking age. State-specific trends allow each state its own baseline trajectory, so the DD estimate captures deviations from that trajectory.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike allowing each student in a class to have their own grade trend (some improving, some declining) before a new teaching method is introduced. The method's effect is the change in trajectory, not just the change in level.\n:::\n::::\n:::::\n\n**Clustered Standard Errors:** Standard errors that account for correlation among observations within the same cluster (e.g., state, school, firm) over time. Without clustering, standard errors are too small and significance tests are unreliable.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nDeath rates within the same state are correlated over time (a state with high rates one year tends to have high rates the next). Clustering by state corrects for this serial correlation.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike recognizing that poll responses from members of the same family are not truly independent. If you count each family member as a separate opinion, you overstate how much information you have.\n:::\n::::\n:::::\n\n**Serial Correlation:** The tendency for a variable measured over time within the same unit (person, state, firm) to be correlated with its own past values. Positive serial correlation means high values tend to be followed by high values.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nA state with a high death rate in 1975 likely has a high rate in 1976 too, because the underlying factors (demographics, road conditions) change slowly.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike the weather. Today's temperature is a good predictor of tomorrow's --- hot days tend to follow hot days. Ignoring this correlation would make you overconfident in your forecasts.\n:::\n::::\n:::::\n\n**Average Treatment Effect on the Treated (ATT):** The average causal effect of treatment specifically for the group that actually received treatment. DD typically estimates the ATT, not the ATE for the whole population.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nThe DD estimate of the MLDA's effect on mortality applies to the states that actually changed their drinking laws, not to all states in the country.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike measuring how much a new exercise routine helped the people who actually did it, rather than averaging across everyone including those who never exercised.\n:::\n::::\n:::::\n\n**Staggered Adoption:** A setting where different units (states, firms) adopt a policy at different times, creating multiple treatment-control comparisons. This is the typical setting for DD in practice.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nDifferent U.S. states lowered their drinking age to 18 at different points between 1970 and 1975, then raised it back to 21 at different points in the 1980s.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike a chain of restaurants rolling out a new menu one location at a time over several months. Each new location becomes \"treated\" while the others serve as controls --- for now.\n:::\n::::\n:::::\n\n**Panel Data:** A dataset that tracks the same units (individuals, states, firms) across multiple time periods. Panel data is the natural structure for DD because it allows researchers to observe changes within units over time.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nA dataset with death rates for each of 51 states in each year from 1970 to 1983 (51 states x 14 years = 714 observations).\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike a class roster where the teacher records each student's grade on every test throughout the year. Following the same students over time reveals individual trajectories, not just snapshots.\n:::\n::::\n:::::\n\n**Policy Variation:** Differences in policy across groups (states, countries) or over time that create the variation researchers exploit for causal identification. Without policy variation, there is nothing to compare.\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n::: {.callout-tip collapse=\"true\" appearance=\"simple\" title=\"Example\"}\nThe fact that some states set the drinking age at 18 while others kept it at 21 creates policy variation that DD exploits.\n:::\n::::\n:::: {.column width=\"50%\"}\n::: {.callout-note collapse=\"true\" appearance=\"simple\" title=\"Analogy\"}\nLike a patchwork quilt where each square is a different color. The variation in colors (policies) across squares (states) is what lets you study the effect of a particular color on warmth.\n:::\n::::\n:::::\n\n\n## A Mississippi Experiment\n\n### The Great Depression and the Fed\n\nIn 1930, the collapse of Caldwell and Company, a Nashville banking giant, triggered a cascade of bank failures across the American South. Within weeks, dozens of banks closed. The question for policymakers: **could aggressive central bank intervention have prevented the collapse?**\n\nA natural experiment emerged from the structure of the Federal Reserve System. The border between two Fed districts runs through Mississippi, splitting the state between:\n\n- **6th District (Atlanta Fed)**: favored easy credit and liquidity support for struggling banks\n- **8th District (St. Louis Fed)**: followed a restrictive \"Real Bills\" doctrine, tightening credit during the crisis\n\nBanks on either side of this border faced the same economic conditions but received very different policy responses.\n\n::: {#c57671f5 .cell execution_count=1}\n``` {.python .cell-code}\n# Load clean bank failure data (July 1 each year, both districts)\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport statsmodels.formula.api as smf\nsns.set_style(\"whitegrid\")\n\n# --- Data source ---\nDATA = \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/\"\n\n# bib6 = banks in business (6th district), bib8 = banks in business (8th district)\n# counterfactual = what 6th district would look like under parallel trends\nbanks = pd.read_csv(DATA + \"ch5/banks_clean.csv\")\nbanks\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>bib6</th>\n      <th>bib8</th>\n      <th>counterfactual</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1929</td>\n      <td>141</td>\n      <td>169</td>\n      <td>141</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1930</td>\n      <td>135</td>\n      <td>165</td>\n      <td>135</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1931</td>\n      <td>121</td>\n      <td>132</td>\n      <td>102</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1932</td>\n      <td>113</td>\n      <td>120</td>\n      <td>90</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1933</td>\n      <td>102</td>\n      <td>111</td>\n      <td>81</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1934</td>\n      <td>102</td>\n      <td>109</td>\n      <td>79</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Visualizing the DD\n\n::: {#cell-fig-banks .cell execution_count=2}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(9, 5))\n\n# Plot actual data for both districts\nax.plot(banks[\"year\"], banks[\"bib8\"], \"ko-\", markersize=8, label=\"8th District (no intervention)\")\nax.plot(banks[\"year\"], banks[\"bib6\"], \"ks-\", markersize=8, label=\"6th District (Fed intervention)\")\nax.plot(banks[\"year\"], banks[\"counterfactual\"], \"k^--\", markersize=8, alpha=0.6,\n        label=\"6th District counterfactual\")\n\nax.set_xlabel(\"Year\")\nax.set_ylabel(\"Number of Banks in Business\")\nax.set_title(\"Fed intervention and bank survival during the Great Depression\")\nax.legend()\nax.set_ylim(60, 180)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Banks in business in the 6th and 8th Federal Reserve Districts, with DD counterfactual. The dashed line shows what would have happened to the 6th District without intervention.](05-differences-in-differences_files/figure-html/fig-banks-output-1.png){#fig-banks width=854 height=470}\n:::\n:::\n\n\nThe divergence is striking. Both districts started with roughly similar numbers of banks in 1930. After the crisis hit, the 8th District (no intervention) lost banks rapidly, while the 6th District (Fed intervention) held up much better. The dashed counterfactual line shows where the 6th District would have ended up if it had followed the same trajectory as the 8th --- the gap between the actual and counterfactual lines is the DD estimate of how many banks the Fed saved.\n\n### Computing the DD\n\nLet's quantify this visual impression. The DD calculation compares **changes** across groups, which removes any fixed differences between the districts:\n\n::: {#tbl-dd-calc .cell tbl-cap='Difference-in-differences calculation for bank survival. The DD estimate represents the causal effect of Fed intervention.' execution_count=3}\n``` {.python .cell-code}\n# Compute DD for each post-crisis year\n# Get the 1930 baseline values for each district\npre_6 = banks.loc[banks[\"year\"] == 1930, \"bib6\"].values[0]\npre_8 = banks.loc[banks[\"year\"] == 1930, \"bib8\"].values[0]\n\n# Loop over each year after 1930\nrows = []\npost_years = banks[banks[\"year\"] > 1930]\nfor _, row in post_years.iterrows():\n    # Change in each district relative to 1930\n    change_6 = row[\"bib6\"] - pre_6\n    change_8 = row[\"bib8\"] - pre_8\n    # DD = treated change minus control change\n    dd = change_6 - change_8\n\n    rows.append({\n        \"Year\": int(row[\"year\"]),\n        \"Change in 6th (treated)\": int(change_6),\n        \"Change in 8th (control)\": int(change_8),\n        \"DD estimate (banks saved)\": int(dd),\n    })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Year</th>\n      <th>Change in 6th (treated)</th>\n      <th>Change in 8th (control)</th>\n      <th>DD estimate (banks saved)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1931</td>\n      <td>-14</td>\n      <td>-33</td>\n      <td>19</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1932</td>\n      <td>-22</td>\n      <td>-45</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1933</td>\n      <td>-33</td>\n      <td>-54</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1934</td>\n      <td>-33</td>\n      <td>-56</td>\n      <td>23</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-important}\n### Key finding\n\nThe Atlanta Fed's easy money policy saved approximately **19--23 banks** relative to the restrictive St. Louis Fed approach. The DD works by subtracting the control group's change from the treated group's change, removing any common trends.\n:::\n\n::: {.callout-note}\n### Intuition Builder: The Diet Analogy\n\nSuppose you and a friend both plan to eat well over the holidays. You go on a new diet; your friend doesn't. After the holidays, you gained 2 lbs and your friend gained 7 lbs. Did the diet work?\n\n- **Naive comparison**: You weigh more than before (gained 2 lbs) --- diet \"failed\"?\n- **DD comparison**: You gained 2, your friend gained 7. The diet saved you 5 lbs (7 − 2 = 5).\n\nThe key assumption: without the diet, you would have gained the same 7 lbs as your friend (parallel trends). DD uses the control group to estimate this counterfactual.\n:::\n\n\n## The DD Framework\n\n### The Core Logic\n\nDD compares changes over time in a treatment group with changes in a control group:\n\n$$\\delta_{DD} = \\underbrace{(\\bar{Y}_{treat,after} - \\bar{Y}_{treat,before})}_{\\text{Change in treated}} - \\underbrace{(\\bar{Y}_{control,after} - \\bar{Y}_{control,before})}_{\\text{Change in control}}$$\n\n```{mermaid}\n%%| label: fig-dd-logic\n%%| fig-cap: \"The DD method: subtract the control group's change from the treated group's change to isolate the causal effect.\"\n\ngraph TD\n    T1[\"Treated group: BEFORE\"]\n    T2[\"Treated group: AFTER\"]\n    C1[\"Control group: BEFORE\"]\n    C2[\"Control group: AFTER\"]\n    DT[\"Change in treated\"]\n    DC[\"Change in control\"]\n    DD[\"DD = Change in treated minus change in control\"]\n\n    T1 --> DT\n    T2 --> DT\n    C1 --> DC\n    C2 --> DC\n    DT --> DD\n    DC --> DD\n\n    style T1 fill:#475569,color:#fff\n    style T2 fill:#475569,color:#fff\n    style C1 fill:#475569,color:#fff\n    style C2 fill:#475569,color:#fff\n    style DD fill:#2d8659,color:#fff\n    style DT fill:#3498db,color:#fff\n    style DC fill:#e67e22,color:#fff\n    linkStyle default stroke:#64748b,stroke-width:2px\n```\n\n### The Parallel Trends Assumption\n\n::: {.callout-warning}\n### The key assumption\n\nDD requires that, **absent treatment**, the treated and control groups would have followed **parallel trends**. The treatment and control groups can start at different levels --- but their *changes over time* must be similar.\n\nIf this assumption fails (e.g., the treated group was already on a different trajectory), the DD estimate will be biased.\n:::\n\n::: {.callout-warning}\n### Common Misconception: DD does NOT require equal levels\n\nStudents often think DD requires the treatment and control groups to have the same *level* of the outcome. This is wrong. The 6th District had 135 banks and the 8th had 165 --- very different levels. What matters is that they would have *changed at the same rate* without the intervention. Groups can start miles apart; DD only needs them to travel in the same direction at the same speed.\n:::\n\n\n## Case Study: MLDA and Death Rates\n\n### The Policy Variation\n\nAfter Prohibition ended in 1933, states set their own drinking ages. In 1984, federal legislation pushed all states to adopt a minimum legal drinking age of 21, but states complied at different times. This staggered adoption creates variation for a DD analysis.\n\n::: {#827dcfdb .cell execution_count=4}\n``` {.python .cell-code}\n# Load clean MLDA death rate data (state-year panel, 18-20 year olds, 1970-1983)\n# mrate = death rate per 100,000; legal = fraction of 18-20 yr olds who can legally drink\n# dtype = cause of death (all, MVA, suicide, internal); pop = state population of 18-20 yr olds\ndeaths = pd.read_csv(DATA + \"ch5/deaths_clean.csv\")\ndeaths.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>state</th>\n      <th>dtype</th>\n      <th>mrate</th>\n      <th>legal</th>\n      <th>pop</th>\n      <th>beertax</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1970</td>\n      <td>1</td>\n      <td>all</td>\n      <td>153.870470</td>\n      <td>0.0</td>\n      <td>189770</td>\n      <td>1.373711</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1970</td>\n      <td>1</td>\n      <td>MVA</td>\n      <td>62.180534</td>\n      <td>0.0</td>\n      <td>189770</td>\n      <td>1.373711</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1970</td>\n      <td>1</td>\n      <td>suicide</td>\n      <td>2.107815</td>\n      <td>0.0</td>\n      <td>189770</td>\n      <td>1.373711</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### The Regression DD Model\n\nWith many states and years, DD is implemented as a regression with **fixed effects**:\n\n$$Y_{st} = \\alpha + \\delta \\, D_{st} + \\sum_s \\beta_s \\, \\text{STATE}_s + \\sum_t \\gamma_t \\, \\text{YEAR}_t + e_{st}$$\n\nwhere $Y_{st}$ is the death rate (`mrate`) in state $s$ at time $t$, and $D_{st}$ is the fraction of 18--20 year olds who can legally drink (`legal`).\n\n- **State fixed effects** ($\\beta_s$) absorb permanent differences between states (culture, geography, road conditions)\n- **Year fixed effects** ($\\gamma_t$) absorb nationwide trends (vehicle safety improvements, national campaigns)\n- **$\\delta$** is the DD estimate: the causal effect of legal drinking access on the death rate\n\n::: {.callout-note}\n### Why cluster standard errors by state?\n\nThe treatment variable (`legal`) changes at the state level, and death rates within a state are correlated over time. **Clustering** standard errors at the state level accounts for this serial correlation, preventing us from overstating precision.\n:::\n\nLet's start with a single regression for all-cause mortality:\n\n::: {#tbl-dd-example .cell tbl-cap='Regression DD: effect of legal drinking access on all-cause death rates among 18-20 year olds (with state and year fixed effects, clustered SEs).' execution_count=5}\n``` {.python .cell-code}\n# Filter to all-cause deaths\nallcause = deaths[deaths[\"dtype\"] == \"all\"]\n\n# DD regression with state and year fixed effects\nmodel = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=allcause)\n\n# Cluster standard errors by state because treatment (legal) varies at the state level\nresult = model.fit(cov_type=\"cluster\", cov_kwds={\"groups\": allcause[\"state\"]})\n\n# Show just the key coefficient\ncoef_table = pd.DataFrame({\n    \"Variable\": [\"legal\"],\n    \"Coefficient\": [round(result.params[\"legal\"], 2)],\n    \"Std. Error\": [round(result.bse[\"legal\"], 2)],\n    \"t-stat\": [round(result.tvalues[\"legal\"], 2)],\n})\ncoef_table\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Variable</th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n      <th>t-stat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>legal</td>\n      <td>10.8</td>\n      <td>4.59</td>\n      <td>2.35</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe `legal` coefficient tells us that a one-unit increase in the fraction of 18--20 year olds who can legally drink is associated with approximately **8--12 additional deaths per 100,000**. The t-statistic exceeds 2, confirming statistical significance. But does this finding hold up across different causes of death and model specifications? Let's check:\n\n::: {#tbl-dd-full .cell tbl-cap='Regression DD estimates of MLDA effects on death rates across causes and specifications. Standard errors clustered at the state level.' execution_count=6}\n``` {.python .cell-code}\n# Compare three specifications for each cause of death:\n#   Spec 1 — Unweighted OLS with state + year fixed effects\n#   Spec 2 — Add state-specific linear trends (each state gets its own slope over time)\n#   Spec 3 — Population-weighted WLS (larger states count more)\n\ndtype_labels = {\"all\": \"All causes\", \"MVA\": \"Motor vehicle\", \"suicide\": \"Suicide\", \"internal\": \"Internal\"}\n\nrows = []\nfor dtype_val, label in dtype_labels.items():\n    s = deaths[deaths[\"dtype\"] == dtype_val].copy()\n\n    # Spec 1: State + Year FE, unweighted\n    model1 = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=s)\n    r1 = model1.fit(cov_type=\"cluster\", cov_kwds={\"groups\": s[\"state\"]})\n\n    # Spec 2: Add state-specific linear trends\n    # C(state):year = interaction of state dummies with year, giving each state its own slope\n    model2 = smf.ols(\"mrate ~ legal + C(state) + C(year) + C(state):year\", data=s)\n    r2 = model2.fit(cov_type=\"cluster\", cov_kwds={\"groups\": s[\"state\"]})\n\n    # Spec 3: Population-weighted (WLS)\n    # Weight by state population so larger states count more (more reliable death rates)\n    model3 = smf.wls(\"mrate ~ legal + C(state) + C(year)\", data=s, weights=s[\"pop\"])\n    r3 = model3.fit(cov_type=\"cluster\", cov_kwds={\"groups\": s[\"state\"]})\n\n    # Format each result as \"coefficient (standard error)\"\n    coef1 = format(round(r1.params[\"legal\"], 2), \".2f\") + \" (\" + format(round(r1.bse[\"legal\"], 2), \".2f\") + \")\"\n    coef2 = format(round(r2.params[\"legal\"], 2), \".2f\") + \" (\" + format(round(r2.bse[\"legal\"], 2), \".2f\") + \")\"\n    coef3 = format(round(r3.params[\"legal\"], 2), \".2f\") + \" (\" + format(round(r3.bse[\"legal\"], 2), \".2f\") + \")\"\n\n    rows.append({\n        \"Cause\": label,\n        \"Unweighted\": coef1,\n        \"With state trends\": coef2,\n        \"Pop. weighted\": coef3,\n    })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Cause</th>\n      <th>Unweighted</th>\n      <th>With state trends</th>\n      <th>Pop. weighted</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>All causes</td>\n      <td>10.80 (4.59)</td>\n      <td>8.47 (5.10)</td>\n      <td>12.41 (4.60)</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Motor vehicle</td>\n      <td>7.59 (2.50)</td>\n      <td>6.64 (2.66)</td>\n      <td>7.50 (2.27)</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Suicide</td>\n      <td>0.59 (0.59)</td>\n      <td>0.47 (0.80)</td>\n      <td>1.49 (0.88)</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Internal</td>\n      <td>1.33 (1.59)</td>\n      <td>0.08 (1.93)</td>\n      <td>1.89 (1.78)</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-important}\n### Interpreting the DD results\n\n- **Legal drinking access increases the death rate** by approximately **8--12 per 100,000** among 18--20 year olds\n- **Motor vehicle accidents** account for most of the effect (~7--8 deaths)\n- **Internal causes** (disease) show no significant effect --- a **placebo test** confirming the design\n- Results are **robust** to adding state-specific trends and population weighting\n:::\n\n\n## Robustness Checks\n\nThe baseline results are encouraging, but how confident can we be? A careful researcher should probe whether the findings hold up under alternative specifications.\n\n### State-Specific Trends\n\nAdding state-specific linear time trends is a more demanding test. It allows each state to have its own background trajectory and asks whether the MLDA effect is a **deviation from this trend** rather than a continuation of pre-existing patterns. The results hold up.\n\n### Beer Tax Control\n\nAnother potential confounder is beer taxes, which some states changed around the same time as their drinking age laws. If beer taxes independently affect mortality, omitting them could bias the DD estimate. Controlling for beer taxes tests whether the MLDA effect is confounded by these concurrent policy changes:\n\n::: {#tbl-beertax .cell tbl-cap='DD estimates controlling for beer taxes. MLDA effects remain robust.' execution_count=7}\n``` {.python .cell-code}\n# Check if MLDA effects hold after controlling for beer taxes\nrows = []\nfor dtype_val, label in [(\"all\", \"All causes\"), (\"MVA\", \"Motor vehicle\")]:\n    s = deaths[deaths[\"dtype\"] == dtype_val].dropna(subset=[\"beertax\"]).copy()\n\n    model = smf.ols(\"mrate ~ legal + beertax + C(state) + C(year)\", data=s)\n    # Cluster standard errors by state\n    r = model.fit(cov_type=\"cluster\", cov_kwds={\"groups\": s[\"state\"]})\n\n    # Format results as \"coefficient (standard error)\"\n    legal_str = format(round(r.params[\"legal\"], 2), \".2f\") + \" (\" + format(round(r.bse[\"legal\"], 2), \".2f\") + \")\"\n    tax_str = format(round(r.params[\"beertax\"], 2), \".2f\") + \" (\" + format(round(r.bse[\"beertax\"], 2), \".2f\") + \")\"\n\n    rows.append({\n        \"Cause\": label,\n        \"Legal effect\": legal_str,\n        \"Beer tax effect\": tax_str,\n    })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Cause</th>\n      <th>Legal effect</th>\n      <th>Beer tax effect</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>All causes</td>\n      <td>10.98 (4.69)</td>\n      <td>1.51 (9.07)</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Motor vehicle</td>\n      <td>7.59 (2.56)</td>\n      <td>3.82 (5.40)</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe MLDA coefficients are largely unchanged after controlling for beer taxes, reinforcing the causal interpretation.\n\n\n## How DD Compares to Other Methods\n\nWe now have four causal inference tools in our toolkit. How do they relate to each other?\n\n| Feature | RCT (Ch 1) | IV (Ch 3) | RD (Ch 4) | **DD (This Chapter)** |\n|:---|:---|:---|:---|:---|\n| **Key requirement** | Random assignment | Valid instrument | Sharp cutoff | Parallel trends |\n| **Handles unobservables?** | Yes (by randomization) | Yes (via instrument) | Yes (at the cutoff) | Only time-invariant ones |\n| **Estimates** | ATE | LATE (compliers) | Local effect (at cutoff) | ATT (treated group) |\n| **Data structure** | Cross-section | Cross-section or panel | Running variable | Panel (group × time) |\n\n: Comparing the four causal inference methods covered so far {.striped}\n\n::: {.callout-note}\n### Connection to Chapters 1 and 4\n\nDD complements the other methods:\n\n- **vs. RCTs (Chapter 1)**: DD works when randomization is impossible but policy varies across groups and time. It sacrifices the randomization guarantee for broader applicability.\n- **vs. RD (Chapter 4)**: Both exploit policy rules, but RD uses a cutoff in a running variable while DD uses changes over time. The MLDA question appears in *both* chapters: Chapter 4 uses the age-21 cutoff (RD); this chapter uses state-level policy changes over time (DD). Same question, different identification strategies.\n:::\n\n\n## Historical Perspective: John Snow\n\nThe logic of DD has a surprisingly long history.\n\nLong before modern econometrics, **John Snow** (1813--1858) used DD reasoning to solve one of the great public health mysteries: the cause of cholera.\n\nIn 1854 London, Snow noticed that cholera deaths were concentrated in neighborhoods served by the **Southwark and Vauxhall** water company, which drew from a contaminated stretch of the Thames. A competing company, **Lambeth**, had moved its intake upstream to cleaner water in 1852.\n\nSnow compared the *change* in cholera death rates before and after Lambeth's move, relative to Southwark and Vauxhall's unchanged source. The dramatic decline in Lambeth-served neighborhoods --- with no corresponding decline in Southwark areas --- provided compelling evidence that contaminated water caused cholera, overturning the prevailing \"miasma\" (bad air) theory.\n\nThis was a DD analysis avant la lettre: two groups (water companies), a treatment that changed for one but not the other, and a comparison of changes in outcomes.\n\n\n## Key Takeaways\n\nThe following concept map shows how the key ideas in this chapter connect --- from policy variation across groups and time, through the DD method and its parallel trends assumption, to regression implementation with fixed effects and robustness checks.\n\n```{mermaid}\n%%| label: fig-concept-map\n%%| fig-cap: \"How the key concepts of Chapter 5 connect\"\n\ngraph TD\n    Q[\"Policy varies across groups and time\"]\n    DD[\"DD: compare changes in treated vs. control\"]\n    PT[\"Parallel trends assumption must hold\"]\n    FE[\"Regression with state and year fixed effects\"]\n    ROB[\"Robustness: trends, weights, placebos\"]\n    EV[\"Evidence: Fed saved banks; MLDA increases deaths\"]\n\n    Q --> DD\n    DD --> PT\n    DD --> FE\n    FE --> ROB\n    ROB --> EV\n\n    style Q fill:#3498db,color:#fff\n    style DD fill:#8e44ad,color:#fff\n    style PT fill:#c0392b,color:#fff\n    style FE fill:#e67e22,color:#fff\n    style ROB fill:#475569,color:#fff\n    style EV fill:#2d8659,color:#fff\n    linkStyle default stroke:#64748b,stroke-width:2px\n```\n\n1. **DD compares changes over time** between treatment and control groups, removing time-invariant confounders.\n\n2. **The parallel trends assumption** is key: absent treatment, both groups must have been on the same trajectory.\n\n3. **Regression DD with fixed effects** is the standard implementation for multi-group, multi-period settings.\n\n4. **State fixed effects** remove permanent state differences; **year fixed effects** remove common time trends.\n\n5. **Cluster standard errors** at the level of treatment assignment (e.g., state) to account for serial correlation.\n\n6. **Robustness checks** include state-specific trends, population weighting, and placebo tests on unaffected outcomes.\n\n\n## Learn by Coding\n\nCopy this code into a Python notebook to reproduce the key results from this chapter.\n\n```python\n# ============================================================\n# Chapter 5: Differences-in-Differences — Code Cheatsheet\n# ============================================================\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\nDATA = \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/\"\n\n# --- Step 1: Manual DD with the Great Depression banking data ---\nbanks = pd.read_csv(DATA + \"ch5/banks_clean.csv\")\nprint(\"Banks in business by district and year:\")\nprint(banks)\n\npre_6 = banks.loc[banks[\"year\"] == 1930, \"bib6\"].values[0]\npre_8 = banks.loc[banks[\"year\"] == 1930, \"bib8\"].values[0]\npost_6 = banks.loc[banks[\"year\"] == 1931, \"bib6\"].values[0]\npost_8 = banks.loc[banks[\"year\"] == 1931, \"bib8\"].values[0]\ndd = (post_6 - pre_6) - (post_8 - pre_8)\nprint(f\"\\nDD estimate (1931 vs 1930): {dd} banks saved by Atlanta Fed intervention\")\n\n# --- Step 2: Load MLDA death rate panel data ---\ndeaths = pd.read_csv(DATA + \"ch5/deaths_clean.csv\")\nallcause = deaths[deaths[\"dtype\"] == \"all\"]\nprint(f\"\\nDeath rate panel: {allcause.shape[0]} state-year observations\")\n\n# --- Step 3: Regression DD with state and year fixed effects ---\nmodel = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=allcause)\nresult = model.fit(cov_type=\"cluster\", cov_kwds={\"groups\": allcause[\"state\"]})\nprint(f\"\\nDD estimate (all-cause deaths): {round(result.params['legal'], 2)}\")\nprint(f\"  Standard error: {round(result.bse['legal'], 2)}\")\n\n# --- Step 4: Population-weighted DD ---\nmodel = smf.wls(\"mrate ~ legal + C(state) + C(year)\", data=allcause, weights=allcause[\"pop\"])\nresult = model.fit(cov_type=\"cluster\", cov_kwds={\"groups\": allcause[\"state\"]})\nprint(f\"\\nWeighted DD estimate: {round(result.params['legal'], 2)}\")\n\n# --- Step 5: Placebo test (suicide should NOT respond to drinking age) ---\nsuicide = deaths[deaths[\"dtype\"] == \"suicide\"]\nmodel = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=suicide)\nresult = model.fit(cov_type=\"cluster\", cov_kwds={\"groups\": suicide[\"state\"]})\nprint(f\"\\nPlacebo (suicide): {round(result.params['legal'], 2)}\")\nprint(\"  (Expect: small and insignificant)\")\n```\n\n::: {.callout-tip}\n### Try it yourself!\nCopy the code above and paste it into [this Google Colab scratchpad](https://colab.research.google.com/notebooks/empty.ipynb) to run it interactively. Modify the variables, change the specifications, and see how results change!\n:::\n\nBelow is the same cheatsheet in Stata syntax.\n\n```stata\n* ============================================================\n* Chapter 5: Differences-in-Differences — Stata Cheatsheet\n* ============================================================\nclear all\nset more off\n\n* --- Step 1: Manual DD with the Great Depression banking data ---\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/banks_clean.csv\", clear\nlist\nscalar pre_6  = bib6[2]   // District 6 in 1930\nscalar pre_8  = bib8[2]   // District 8 in 1930\nscalar post_6 = bib6[3]   // District 6 in 1931\nscalar post_8 = bib8[3]   // District 8 in 1931\nscalar dd = (post_6 - pre_6) - (post_8 - pre_8)\ndisplay \"DD estimate (1931 vs 1930): \" dd \" banks saved by Atlanta Fed\"\n\n* --- Step 2: Load MLDA death rate panel data ---\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/deaths_clean.csv\", clear\nkeep if dtype == \"all\"\n\n* --- Step 3: Regression DD with state and year fixed effects ---\nreg mrate legal i.state i.year, cluster(state)\n\n* --- Step 4: Population-weighted DD ---\nreg mrate legal i.state i.year [aw=pop], cluster(state)\n\n* --- Step 5: Placebo test (suicide should NOT respond to drinking age) ---\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/deaths_clean.csv\", clear\nkeep if dtype == \"suicide\"\nreg mrate legal i.state i.year, cluster(state)\n* Expect: small and insignificant coefficient on legal\n```\n\n::: {.callout-tip}\n### Try it in Stata!\nCopy the code above into a `.do` file and run it in Stata 14 or later (which supports loading data from URLs). If your Stata cannot access the internet, download the CSV files from the `data/` folder on [GitHub](https://github.com/cmg777/intro2causal/tree/main/data) and replace each URL with a local file path.\n:::\n\n\n## Exercises\n\n### Multiple Choice Questions\n\n1. **The key identifying assumption of differences-in-differences is:**\n   a) Treatment and control groups have the same level of the outcome variable\n   b) Treatment is randomly assigned\n   c) Absent treatment, both groups would have followed parallel trends over time\n   d) The treatment effect is constant across all individuals\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(c)** The parallel trends assumption states that, without the treatment, the treated and control groups would have changed at the same rate. **(a) is wrong** because DD allows the groups to start at different levels — that is precisely why we take differences. **(b) is wrong** because random assignment describes RCTs, not DD; DD exploits policy changes in observational data. **(d) is wrong** because DD does not require the same treatment effect for everyone. The key requirement is parallel *trends*, not equal levels, randomization, or homogeneous effects.\n:::\n\n2. **Why does DD subtract the control group's change from the treated group's change?**\n   a) To increase the sample size\n   b) To remove common time trends that affect both groups equally\n   c) To correct for measurement error\n   d) To make the treatment and control groups the same size\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(b)** Both groups may be affected by common shocks (e.g., a national recession, improving vehicle safety). By subtracting the control group's change, DD removes these common trends, isolating the treatment effect. **(a) is wrong** because a single before-after comparison for the treated group cannot distinguish the treatment effect from time trends that affect everyone. **(c) is wrong** because comparing treated and control groups at one point in time conflates the treatment effect with pre-existing level differences. **(d) is wrong** because DD does not require equal group sizes — it relies on the parallel trends assumption instead.\n:::\n\n3. **In the Great Depression banking study, what was the \"treatment\"?**\n   a) The collapse of Caldwell and Company\n   b) The Atlanta Fed's easy-credit intervention for struggling banks\n   c) The creation of the Federal Reserve System\n   d) The end of the gold standard\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(b)** The treatment was the Atlanta Fed's (6th District) policy of providing easy credit and liquidity support to struggling banks, in contrast to the St. Louis Fed's (8th District) restrictive approach. **(a) is wrong** because the Caldwell collapse was the triggering event (common shock), not the treatment — it affected both districts. **(c) is wrong** because the Federal Reserve System was created in 1913, long before the study period. **(d) is wrong** because the end of the gold standard is a macroeconomic event unrelated to the district-level policy comparison.\n:::\n\n4. **State fixed effects in a DD regression control for:**\n   a) Changes in state policies over time\n   b) Permanent differences between states that do not change over time\n   c) The interaction between state and year\n   d) Differences between treatment and control states after treatment\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(b)** State fixed effects absorb all characteristics of a state that are constant over time — geography, culture, climate, institutional history, etc. They allow us to compare changes *within* each state over time, rather than comparing levels across states. **(a) is wrong** because it describes state-specific time trends (which allow each state its own slope over time), a more demanding specification than simple fixed effects. **(c) is wrong** because it describes an interaction term between treatment and time, which is the DD coefficient itself, not a fixed effect. **(d) is wrong** because fixed effects do not eliminate measurement error in the dependent variable — they only remove time-invariant confounders.\n:::\n\n5. **If the parallel trends assumption is violated, the DD estimate will be:**\n   a) Exactly zero\n   b) Unbiased but imprecise\n   c) Biased — it will confound the treatment effect with pre-existing differential trends\n   d) Valid only for the treated group\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(c)** If the treated group was already on a different trajectory before treatment, the DD estimate captures both the treatment effect and this pre-existing trend difference — a violation of the parallel trends assumption. **(a) is wrong** because heteroscedasticity affects standard errors but does not bias the DD point estimate. **(b) is wrong** because unequal group sizes reduce precision but do not inherently bias the estimate. **(d) is wrong** because a single pre-treatment observation is insufficient to detect diverging trends; multiple pre-treatment periods are needed to assess whether parallel trends hold.\n:::\n\n6. **Year fixed effects in a DD regression control for:**\n   a) Differences between states that are constant over time\n   b) Shocks or trends that affect all states equally in a given year\n   c) The treatment effect itself\n   d) Measurement error in the outcome variable\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(b)** Year fixed effects absorb common shocks — economy-wide recessions, nationwide policy changes, or secular trends in mortality — that affect all states in the same year. Without year fixed effects, these common trends could be mistaken for treatment effects. **(a) is wrong** because that describes state fixed effects, not year fixed effects. **(c) is wrong** because the treatment effect is captured by the interaction of treatment group and post-treatment period, not by year fixed effects. **(d) is wrong** because fixed effects do not correct measurement error.\n:::\n\n7. **Clustering standard errors at the state level in a DD regression is important because:**\n   a) It increases the statistical significance of the estimates\n   b) Outcomes within the same state are correlated across years, and ignoring this understates standard errors\n   c) It makes the regression coefficients unbiased\n   d) It is required whenever the sample size is large\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(b)** Within a state, outcomes are correlated over time (serial correlation). If we ignore this and treat each state-year as independent, we understate the true uncertainty and get artificially small standard errors, leading to false rejections of the null. Clustering at the state level corrects for this. **(a) is wrong** because clustering typically makes results *less* significant by increasing standard errors. **(c) is wrong** because clustering affects standard errors and inference, not the point estimates. **(d) is wrong** because clustering is motivated by the data structure (repeated observations within units), not by sample size.\n:::\n\n8. **Adding state-specific linear time trends to a DD regression:**\n   a) Is always necessary for a valid DD estimate\n   b) Allows each state to have its own pre-treatment trajectory, testing whether DD results survive this stricter control\n   c) Eliminates the need for the parallel trends assumption\n   d) Has no effect on the treatment coefficient\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(b)** State-specific trends allow each state its own linear slope over time. If the DD estimate is robust to adding these trends, it suggests the result is not driven by pre-existing divergent trajectories. If the estimate changes substantially, the parallel trends assumption may be suspect. **(a) is wrong** because state trends are a robustness check, not a requirement — many valid DD studies do not include them. **(c) is wrong** because state trends partially address the concern but do not eliminate it; non-linear differential trends could still bias the estimate. **(d) is wrong** because adding state trends often changes the coefficient, sometimes substantially.\n:::\n\n9. **In the MLDA DD analysis, the treatment effect is identified by comparing:**\n   a) States that changed their legal drinking age to states that did not, before and after the change\n   b) Young people to old people in the same state\n   c) States with high drinking rates to states with low drinking rates\n   d) Male mortality to female mortality in the same year\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(a)** The MLDA DD compares changes in mortality in states that lowered their legal drinking age to 18 versus states that kept it at 21, before and after the policy change. The within-state change removes permanent state differences, and the cross-state comparison removes common time trends. **(b) is wrong** because DD compares treatment and control states, not age groups within a state (that would be more like an RD approach). **(c) is wrong** because DD does not compare states by drinking levels but by whether they changed their policy. **(d) is wrong** because comparing across genders is not the DD variation — it could serve as a placebo test, but is not the main identification strategy.\n:::\n\n10. **A placebo test in DD involves:**\n    a) Administering a placebo treatment to the control group\n    b) Testing whether the DD estimate is significant for outcomes that should NOT be affected by the treatment\n    c) Randomly reassigning the treatment variable\n    d) Running the regression without fixed effects\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n**(b)** A placebo test checks whether the DD estimate produces a significant effect on an outcome the treatment should not affect. For example, if a pollution regulation appears to reduce asthma but also \"reduces\" broken bones, the design is suspect. A clean placebo test (no effect on the irrelevant outcome) strengthens the causal interpretation. **(a) is wrong** because DD is observational — there is no literal placebo administered. **(c) is wrong** because randomly reassigning treatment is a permutation test, not a placebo test. **(d) is wrong** because omitting fixed effects changes the specification but is not a placebo test — it would introduce bias rather than test validity.\n:::\n\n### Conceptual Questions\n\n1. **Parallel trends**: A city implements a minimum wage increase in 2020. You plan to compare employment changes in that city with a neighboring city that didn't raise the minimum wage. What would it mean if the two cities already had diverging employment trends before 2020? How would this affect your DD estimate?\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n\n**Diverging pre-treatment trends violate the parallel trends assumption and contaminate the DD estimate with a pre-existing trend difference.**\n\n1. The parallel trends assumption requires that, absent the minimum wage increase, both cities would have followed the same employment trajectory. If the treatment city was already losing jobs faster, this assumption fails.\n2. The DD estimate equals (treatment effect) + (pre-existing trend gap). If employment in the treatment city was already declining by 2 percentage points more per period, the DD would overstate the negative effect of the minimum wage by that amount.\n3. To diagnose this problem, plot employment trends for both cities across multiple pre-treatment periods. If the lines are roughly parallel before the policy change, the assumption is more credible. If they diverge, the DD estimate is unreliable.\n4. A possible fix is to add city-specific linear time trends to the regression, which absorbs pre-existing trend differences and isolates deviations from those trends.\n:::\n\n2. **Computing DD**: Before a policy change, the treatment group's outcome average is 50 and the control group's is 40. After the change, they are 55 and 48. (a) Compute the DD estimate. (b) What assumption is needed for this to be causal?\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n\n**The DD estimate is -3, meaning the treatment caused the outcome to be 3 units lower than it would have been without the policy.**\n\n1. (a) Compute each group's before-after change: Treatment group changed by (55 - 50) = +5. Control group changed by (48 - 40) = +8. The DD estimate is the difference of these changes: 5 - 8 = -3. The treatment group's outcome fell by 3 units relative to the control group's trajectory.\n2. (b) The parallel trends assumption is essential: absent the policy change, both groups would have experienced the same +8 change over time. Under this assumption, the treatment group's counterfactual outcome would have been 50 + 8 = 58. Since the observed outcome was 55, the treatment effect is 55 - 58 = -3, matching the DD calculation.\n3. This example illustrates why a simple before-after comparison for the treated group (showing a +5 increase) would be misleading --- the DD reveals the policy actually *reduced* the outcome by 3 units relative to the counterfactual trend.\n:::\n\n3. **Fixed effects**: Explain in your own words why we need *both* state and year fixed effects in the MLDA regression. What would happen if we omitted state effects? Year effects?\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n\n**State and year fixed effects work together to isolate the within-state, within-year variation in MLDA policy --- the only variation that can credibly identify the causal effect.**\n\n1. State fixed effects (`C(state)`) absorb all time-invariant differences between states --- geography, culture, road infrastructure, baseline drinking norms. Without them, we might attribute Montana's permanently higher death rate to its MLDA policy rather than to its rural roads and long driving distances.\n2. Year fixed effects (`C(year)`) absorb all nationwide changes over time --- improvements in vehicle safety, national campaigns against drunk driving, economic conditions. Without them, a nationwide decline in mortality could be falsely attributed to states that happened to change their MLDA.\n3. Together, they implement the DD logic in a regression framework: we ask whether a state's death rate changed differentially in years when its MLDA policy changed, compared to its own average and compared to the national trend. This is the within-state, within-year variation that identifies the causal effect of MLDA on mortality.\n:::\n\n4. **State-specific trends**: Explain what adding `C(state):year` to the DD regression does. Under what circumstances might the DD estimate change substantially when you add state-specific trends, and what would that imply about the parallel trends assumption?\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n\n**Adding state-specific trends is a more demanding test of the DD design: it asks whether MLDA changes caused deviations from each state's own trajectory, not just from the national average.**\n\n1. The term `C(state):year` gives each state its own linear time trend. Standard DD with year fixed effects only removes the *common* national trend, assuming all states would have followed the same path absent treatment. State-specific trends relax this by allowing each state to have its own baseline trajectory.\n2. If the DD estimate changes substantially after adding state-specific trends, it suggests the standard parallel trends assumption is questionable --- some states were on different trajectories for reasons unrelated to MLDA (e.g., southern states experiencing rapid economic development, or western states with changing demographics).\n3. If the estimate remains stable, it strengthens our confidence in the original DD design, because the result is robust to allowing for differential pre-existing trends across states. This is a useful robustness check, though not a definitive test of parallel trends.\n:::\n\n5. **Placebo test design**: You are studying whether a new air pollution regulation reduced asthma hospitalizations. Propose a placebo outcome that should NOT be affected by the regulation. Why would finding a significant effect on your placebo outcome be concerning?\n\n::: {.callout-note collapse=\"true\"}\n### Show answer\n\n**A placebo outcome should be theoretically unaffected by the treatment; a significant placebo result is a red flag that the DD design is flawed.**\n\n1. Good placebo outcomes for an air pollution regulation include hospitalizations for broken bones, appendicitis, or dental procedures --- conditions with no biological link to air quality.\n2. If the regulation appears to significantly reduce broken-bone hospitalizations, the DD is picking up something other than the treatment effect. This could mean a confounding event coincided with the regulation (e.g., a new hospital opened), or that the treated and control areas were on different trajectories for unrelated reasons (parallel trends violation).\n3. A null placebo result does not *prove* the DD is valid, but it increases confidence by ruling out one class of threats. A significant placebo result is strong evidence against the design, because it demonstrates the DD methodology is attributing non-treatment-related changes to the policy.\n4. This connects to the MLDA analysis in this chapter: the suicide death rate serves a similar placebo-like function, testing whether the DD picks up effects on outcomes less directly linked to legal drinking.\n:::\n\n### Research Tasks\n\n::: {.callout-caution}\n### Research Tasks\n\n1. **DD for suicide deaths**: Using `deaths_clean.csv`, run the DD regression for suicide deaths (`dtype == \"suicide\"`) with state and year fixed effects and state-clustered SEs. Is the effect of legal drinking significant for suicides? How does the coefficient compare to the all-cause result?\n\n2. **DD over time for banks**: Using `banks_clean.csv`, compute the DD estimate for each post-crisis year (1931, 1932, 1933, 1934) relative to the 1930 baseline. Does the effect grow or shrink over time? What does this trend suggest about the lasting impact of the Fed's intervention?\n\n3. **Population-weighted DD**: Using `deaths_clean.csv`, run the all-cause DD regression with population weights (`smf.wls` with `weights=pop`). Compare the coefficient with the unweighted result. Why might weighting by population change the estimate?\n\n4. **Cross-cause DD comparison**: Using `deaths_clean.csv`, run the DD regression (with state and year fixed effects, clustered SEs) separately for each available cause of death: all, MVA, suicide, homicide, and internal. Build a comparison table showing the `legal` coefficient for each. Which causes are plausibly affected by the MLDA, and which serve as placebos?\n\n5. **State-specific trend robustness**: Using `deaths_clean.csv`, run the DD regression for motor vehicle deaths (`dtype == \"MVA\"`) with and without state-specific linear time trends. The baseline model uses `mrate ~ legal + C(state) + C(year)`. The augmented model adds `C(state):year` interactions. How much does the coefficient change? What does this imply about the parallel trends assumption?\n:::\n\n\n## Solutions\n\n### Conceptual Questions\n\n**Q1.** **Diverging pre-treatment trends violate the parallel trends assumption and contaminate the DD estimate with a pre-existing trend difference.**\n\n1. The parallel trends assumption requires that, absent the minimum wage increase, both cities would have followed the same employment trajectory. If the treatment city was already losing jobs faster, this assumption fails.\n2. The DD estimate equals (treatment effect) + (pre-existing trend gap). If employment in the treatment city was already declining by 2 percentage points more per period, the DD would overstate the negative effect of the minimum wage by that amount.\n3. To diagnose this problem, plot employment trends for both cities across multiple pre-treatment periods. If the lines are roughly parallel before the policy change, the assumption is more credible. If they diverge, the DD estimate is unreliable.\n4. A possible fix is to add city-specific linear time trends to the regression, which absorbs pre-existing trend differences and isolates deviations from those trends.\n\n**Q2.** **The DD estimate is -3, meaning the treatment caused the outcome to be 3 units lower than it would have been without the policy.**\n\n1. (a) Compute each group's before-after change: Treatment group changed by (55 - 50) = +5. Control group changed by (48 - 40) = +8. The DD estimate is the difference of these changes: 5 - 8 = -3. The treatment group's outcome fell by 3 units relative to the control group's trajectory.\n2. (b) The parallel trends assumption is essential: absent the policy change, both groups would have experienced the same +8 change over time. Under this assumption, the treatment group's counterfactual outcome would have been 50 + 8 = 58. Since the observed outcome was 55, the treatment effect is 55 - 58 = -3, matching the DD calculation.\n3. This example illustrates why a simple before-after comparison for the treated group (showing a +5 increase) would be misleading --- the DD reveals the policy actually *reduced* the outcome by 3 units relative to the counterfactual trend.\n\n**Q3.** **State and year fixed effects work together to isolate the within-state, within-year variation in MLDA policy --- the only variation that can credibly identify the causal effect.**\n\n1. State fixed effects (`C(state)`) absorb all time-invariant differences between states --- geography, culture, road infrastructure, baseline drinking norms. Without them, we might attribute Montana's permanently higher death rate to its MLDA policy rather than to its rural roads and long driving distances.\n2. Year fixed effects (`C(year)`) absorb all nationwide changes over time --- improvements in vehicle safety, national campaigns against drunk driving, economic conditions. Without them, a nationwide decline in mortality could be falsely attributed to states that happened to change their MLDA.\n3. Together, they implement the DD logic in a regression framework: we ask whether a state's death rate changed differentially in years when its MLDA policy changed, compared to its own average and compared to the national trend. This is the within-state, within-year variation that identifies the causal effect of MLDA on mortality.\n\n**Q4.** **Adding state-specific trends is a more demanding test of the DD design: it asks whether MLDA changes caused deviations from each state's own trajectory, not just from the national average.**\n\n1. The term `C(state):year` gives each state its own linear time trend. Standard DD with year fixed effects only removes the *common* national trend, assuming all states would have followed the same path absent treatment. State-specific trends relax this by allowing each state to have its own baseline trajectory.\n2. If the DD estimate changes substantially after adding state-specific trends, it suggests the standard parallel trends assumption is questionable --- some states were on different trajectories for reasons unrelated to MLDA (e.g., southern states experiencing rapid economic development, or western states with changing demographics).\n3. If the estimate remains stable, it strengthens our confidence in the original DD design, because the result is robust to allowing for differential pre-existing trends across states. This is a useful robustness check, though not a definitive test of parallel trends.\n\n### Research Tasks\n\n**R1.**\n\n::: {#tbl-sol-suicide-dd .cell tbl-cap='DD regression for suicide deaths vs. all-cause deaths' execution_count=8}\n``` {.python .cell-code}\n# --- Setup ---\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\ndeaths = pd.read_csv(DATA + \"ch5/deaths_clean.csv\")\n\n# --- DD Regressions by Cause of Death ---\nrows = []\nfor dtype_val, label in [(\"all\", \"All causes\"), (\"suicide\", \"Suicide\")]:\n    s = deaths[deaths[\"dtype\"] == dtype_val].copy()  # filter to one cause of death\n    r = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=s).fit(\n        cov_type=\"cluster\", cov_kwds={\"groups\": s[\"state\"]})  # cluster SEs by state\n    rows.append({\n        \"Cause\": label,\n        \"Legal effect\": round(r.params[\"legal\"], 2),  # DD estimate of MLDA effect\n        \"SE\": round(r.bse[\"legal\"], 2),\n        \"t-stat\": round(r.tvalues[\"legal\"], 2),  # significance check\n    })\n\n# --- Display Results ---\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Cause</th>\n      <th>Legal effect</th>\n      <th>SE</th>\n      <th>t-stat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>All causes</td>\n      <td>10.80</td>\n      <td>4.59</td>\n      <td>2.35</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Suicide</td>\n      <td>0.59</td>\n      <td>0.59</td>\n      <td>1.00</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nStata equivalent:\n\n```stata\n* --- DD regression: suicide vs. all-cause deaths ---\nclear all\nset more off\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/deaths_clean.csv\", clear\n\n* Encode string variables for fixed effects\nencode dtype, gen(dtype_num)\nencode state, gen(state_num)\n\n* DD for all-cause deaths\npreserve\nkeep if dtype == \"all\"\nreg mrate legal i.state_num i.year, cluster(state_num)\nrestore\n\n* DD for suicide deaths\npreserve\nkeep if dtype == \"suicide\"\nreg mrate legal i.state_num i.year, cluster(state_num)\nrestore\n```\n\n(1) **What the numbers show:** The suicide effect is much smaller than the all-cause effect and is not statistically significant (t-stat well below 2), while the all-cause effect is substantial and significant.\n\n(2) **Why:** Alcohol access primarily increases mortality through motor vehicle accidents, where impaired driving has immediate lethal consequences. Suicide is a more complex outcome driven by mental health, social, and economic factors --- simply being able to buy alcohol legally is unlikely to be a dominant cause.\n\n(3) **What it teaches:** This comparison serves as an informal placebo-like check. If MLDA changes affected suicide rates as strongly as all-cause deaths, we might worry that the DD is picking up a general trend in youth mortality rather than the specific channel of alcohol-related accidents. The null result for suicide strengthens the causal interpretation of the all-cause finding.\n\n**R2.**\n\n::: {#tbl-sol-banks-dd .cell tbl-cap='DD estimate for each post-crisis year relative to 1930' execution_count=9}\n``` {.python .cell-code}\n# --- Setup ---\nbanks = pd.read_csv(DATA + \"ch5/banks_clean.csv\")\n\n# --- Year-by-Year DD Calculations ---\npre = banks[banks[\"year\"] == 1930].iloc[0]  # baseline (pre-crisis) year\nrows = []\nfor _, row in banks[banks[\"year\"] > 1930].iterrows():\n    change_6 = row[\"bib6\"] - pre[\"bib6\"]   # change in treated (6th district, Atlanta Fed)\n    change_8 = row[\"bib8\"] - pre[\"bib8\"]   # change in control (8th district, St. Louis Fed)\n    dd = change_6 - change_8               # DD = treated change minus control change\n\n    rows.append({\n        \"Year\": int(row[\"year\"]),\n        \"Change in 6th (treated)\": int(change_6),\n        \"Change in 8th (control)\": int(change_8),\n        \"DD (banks saved)\": int(dd),  # positive DD means more banks survived in 6th\n    })\n\n# --- Display Results ---\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Year</th>\n      <th>Change in 6th (treated)</th>\n      <th>Change in 8th (control)</th>\n      <th>DD (banks saved)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1931</td>\n      <td>-14</td>\n      <td>-33</td>\n      <td>19</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1932</td>\n      <td>-22</td>\n      <td>-45</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1933</td>\n      <td>-33</td>\n      <td>-54</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1934</td>\n      <td>-33</td>\n      <td>-56</td>\n      <td>23</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nStata equivalent:\n\n```stata\n* --- Year-by-year DD for banks ---\nclear all\nset more off\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/banks_clean.csv\", clear\n\n* Compute DD for each post-crisis year relative to 1930\nsum bib6 if year == 1930\nscalar pre6 = r(mean)\nsum bib8 if year == 1930\nscalar pre8 = r(mean)\n\nforvalues y = 1931/1934 {\n    sum bib6 if year == `y'\n    scalar change6 = r(mean) - pre6\n    sum bib8 if year == `y'\n    scalar change8 = r(mean) - pre8\n    scalar dd = change6 - change8\n    display \"Year `y': DD = \" dd\n}\n```\n\n(1) **What the numbers show:** The DD effect grows from 19 banks in 1931 to 23 in 1932, then remains in the 21--23 range in 1933--1934. Both districts lost banks, but the 8th District (restrictive policy) consistently lost more.\n\n(2) **Why:** The Atlanta Fed's liquidity support prevented bank runs from cascading --- once a bank survived the initial panic with Fed support, it remained solvent through the Depression. The St. Louis Fed's restrictive approach allowed solvent but illiquid banks to fail, and those failures could not be reversed later.\n\n(3) **What it teaches:** This year-by-year DD reveals the *dynamics* of the treatment effect, something a single DD estimate would miss. The growing then stabilizing gap shows that the intervention had both an immediate rescue effect (1931) and a durable protective effect (1932--1934). This pattern supports a causal interpretation: the Fed's policy permanently changed the trajectory of bank survival in its district.\n\n**Q5.** **A placebo outcome should be theoretically unaffected by the treatment; a significant placebo result is a red flag that the DD design is flawed.**\n\n1. Good placebo outcomes for an air pollution regulation include hospitalizations for broken bones, appendicitis, or dental procedures --- conditions with no biological link to air quality.\n2. If the regulation appears to significantly reduce broken-bone hospitalizations, the DD is picking up something other than the treatment effect. This could mean a confounding event coincided with the regulation (e.g., a new hospital opened), or that the treated and control areas were on different trajectories for unrelated reasons (parallel trends violation).\n3. A null placebo result does not *prove* the DD is valid, but it increases confidence by ruling out one class of threats. A significant placebo result is strong evidence against the design, because it demonstrates the DD methodology is attributing non-treatment-related changes to the policy.\n4. This connects to the MLDA analysis in this chapter: the suicide death rate serves a similar placebo-like function, testing whether the DD picks up effects on outcomes less directly linked to legal drinking.\n\n**R3.**\n\n::: {#tbl-sol-wls .cell tbl-cap='Unweighted vs. population-weighted DD for all-cause deaths' execution_count=10}\n``` {.python .cell-code}\n# --- Setup ---\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\ndeaths = pd.read_csv(DATA + \"ch5/deaths_clean.csv\")\nallcause = deaths[deaths[\"dtype\"] == \"all\"]  # keep only all-cause deaths\n\n# --- Unweighted OLS ---\nr_uw = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=allcause).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": allcause[\"state\"]})  # cluster SEs by state\n\n# --- Population-Weighted WLS ---\nr_wt = smf.wls(\"mrate ~ legal + C(state) + C(year)\", data=allcause,\n    weights=allcause[\"pop\"]).fit(  # weight by state population\n    cov_type=\"cluster\", cov_kwds={\"groups\": allcause[\"state\"]})\n\n# --- Display Comparison ---\npd.DataFrame({\n    \"Specification\": [\"Unweighted OLS\", \"Population-weighted WLS\"],\n    \"Legal effect\": [round(r_uw.params[\"legal\"], 2), round(r_wt.params[\"legal\"], 2)],\n    \"SE\": [round(r_uw.bse[\"legal\"], 2), round(r_wt.bse[\"legal\"], 2)],\n})\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Specification</th>\n      <th>Legal effect</th>\n      <th>SE</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Unweighted OLS</td>\n      <td>10.80</td>\n      <td>4.59</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Population-weighted WLS</td>\n      <td>12.41</td>\n      <td>4.60</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nStata equivalent:\n\n```stata\n* --- Unweighted vs. population-weighted DD ---\nclear all\nset more off\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/deaths_clean.csv\", clear\n\nencode state, gen(state_num)\nkeep if dtype == \"all\"\n\n* Unweighted OLS\nreg mrate legal i.state_num i.year, cluster(state_num)\n\n* Population-weighted WLS\nreg mrate legal i.state_num i.year [aw=pop], cluster(state_num)\n```\n\n(1) **What the numbers show:** The two specifications may produce somewhat different point estimates and standard errors, reflecting how weighting shifts influence across states.\n\n(2) **Why:** Population weighting gives more influence to large states (California, Texas, New York) where death rates are measured more precisely due to larger samples. Unweighted OLS treats each state-year equally, giving small states (Wyoming, Vermont) the same weight as large ones. If MLDA effects vary by state size --- for example, if urban states have different drinking cultures --- the two estimates will diverge.\n\n(3) **What it teaches:** Comparing weighted and unweighted estimates is a robustness check. Similar estimates suggest the MLDA effect is consistent across states of different sizes. Divergent estimates reveal heterogeneity and raise the question of which estimate is more policy-relevant: the unweighted estimate answers \"what is the average effect across states?\" while the weighted estimate answers \"what is the effect for the average person?\"\n\n**R4.**\n\n::: {#tbl-sol-cross-cause .cell tbl-cap='DD estimates by cause of death' execution_count=11}\n``` {.python .cell-code}\n# --- Setup ---\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\ndeaths = pd.read_csv(DATA + \"ch5/deaths_clean.csv\")\n\n# --- DD Regression for Each Cause ---\nrows = []\nfor dtype_val, label in [(\"all\", \"All causes\"), (\"MVA\", \"Motor vehicle\"),\n                          (\"suicide\", \"Suicide\"), (\"homicide\", \"Homicide\"),\n                          (\"internal\", \"Internal (placebo)\")]:\n    s = deaths[deaths[\"dtype\"] == dtype_val].copy()\n    if len(s) > 0:\n        r = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=s).fit(\n            cov_type=\"cluster\", cov_kwds={\"groups\": s[\"state\"]})\n        rows.append({\n            \"Cause\": label,\n            \"Legal effect\": round(r.params[\"legal\"], 2),\n            \"SE\": round(r.bse[\"legal\"], 2),\n            \"t-stat\": round(r.tvalues[\"legal\"], 2),\n        })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Cause</th>\n      <th>Legal effect</th>\n      <th>SE</th>\n      <th>t-stat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>All causes</td>\n      <td>10.80</td>\n      <td>4.59</td>\n      <td>2.35</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Motor vehicle</td>\n      <td>7.59</td>\n      <td>2.50</td>\n      <td>3.04</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Suicide</td>\n      <td>0.59</td>\n      <td>0.59</td>\n      <td>1.00</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Homicide</td>\n      <td>0.50</td>\n      <td>0.96</td>\n      <td>0.52</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Internal (placebo)</td>\n      <td>1.33</td>\n      <td>1.59</td>\n      <td>0.84</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nStata equivalent:\n\n```stata\n* --- DD estimates by cause of death ---\nclear all\nset more off\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/deaths_clean.csv\", clear\n\nencode state, gen(state_num)\n\nforeach cause in \"all\" \"MVA\" \"suicide\" \"homicide\" \"internal\" {\n    display \"=== `cause' ===\"\n    preserve\n    keep if dtype == `cause'\n    reg mrate legal i.state_num i.year, cluster(state_num)\n    restore\n}\n```\n\n(1) **What the numbers show:** MVA deaths show the largest and most significant positive effect of legal drinking. All-cause deaths are also significant, reflecting the MVA contribution. Suicide and homicide may show small or insignificant effects. Internal causes (the clean placebo) should show no significant effect.\n\n(2) **Why:** The MLDA primarily affects mortality through drunk driving --- the most direct causal channel from alcohol access to death. Suicide and homicide have partial alcohol channels (impulsivity, aggression) but are driven by many other factors. Internal causes (cancer, heart disease) have no plausible short-term connection to legal drinking age, making them a clean falsification test.\n\n(3) **What it teaches:** This systematic cross-cause comparison is a powerful diagnostic for DD designs. If the `legal` coefficient were large and significant for internal causes, it would suggest the DD is capturing a confounding trend rather than the causal effect of alcohol access. The pattern of results --- strong for MVA, weak for other causes, null for internal --- reinforces the causal interpretation and identifies the primary mechanism (traffic fatalities) through which the MLDA affects mortality.\n\n**R5.**\n\n::: {#tbl-sol-mva-trends .cell tbl-cap='MVA deaths: baseline DD vs. DD with state-specific trends' execution_count=12}\n``` {.python .cell-code}\n# --- Setup ---\ndeaths = pd.read_csv(DATA + \"ch5/deaths_clean.csv\")\nmva = deaths[deaths[\"dtype\"] == \"MVA\"].copy()\n\n# --- Baseline DD ---\nr_base = smf.ols(\"mrate ~ legal + C(state) + C(year)\", data=mva).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": mva[\"state\"]})\n\n# --- DD with State-Specific Linear Time Trends ---\nmva[\"year_num\"] = mva[\"year\"] - mva[\"year\"].min()  # center year for numerical stability\nr_trend = smf.ols(\"mrate ~ legal + C(state) + C(year) + C(state):year_num\", data=mva).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": mva[\"state\"]})\n\n# --- Compare ---\npd.DataFrame({\n    \"Specification\": [\"Baseline DD\", \"DD + state-specific trends\"],\n    \"Legal effect\": [round(r_base.params[\"legal\"], 2), round(r_trend.params[\"legal\"], 2)],\n    \"SE\": [round(r_base.bse[\"legal\"], 2), round(r_trend.bse[\"legal\"], 2)],\n    \"t-stat\": [round(r_base.tvalues[\"legal\"], 2), round(r_trend.tvalues[\"legal\"], 2)],\n})\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Specification</th>\n      <th>Legal effect</th>\n      <th>SE</th>\n      <th>t-stat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Baseline DD</td>\n      <td>7.59</td>\n      <td>2.50</td>\n      <td>3.04</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>DD + state-specific trends</td>\n      <td>6.64</td>\n      <td>2.66</td>\n      <td>2.50</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nStata equivalent:\n\n```stata\n* --- MVA: baseline DD vs. state-specific trends ---\nclear all\nset more off\nimport delimited using \"https://raw.githubusercontent.com/cmg777/intro2causal/main/data/ch5/deaths_clean.csv\", clear\n\nencode state, gen(state_num)\nkeep if dtype == \"MVA\"\n\n* Baseline DD\nreg mrate legal i.state_num i.year, cluster(state_num)\n\n* DD with state-specific linear time trends\nreg mrate legal i.state_num i.year i.state_num#c.year, cluster(state_num)\n```\n\n(1) **What the numbers show:** The coefficient on `legal` may change when state-specific trends are added. If the change is small, the baseline DD is robust. If the coefficient drops substantially or loses significance, the parallel trends assumption may be questionable for MVA deaths.\n\n(2) **Why:** State-specific trends (`C(state):year`) allow each state to follow its own linear trajectory over time. The baseline DD assumes all states would have followed the same mortality trend absent MLDA changes. If some states were already experiencing declining MVA deaths (due to road improvements, vehicle safety, or enforcement) at different rates, the baseline DD could attribute this pre-existing trend to MLDA changes. State-specific trends absorb these differential trajectories.\n\n(3) **What it teaches:** This is the most demanding robustness check in the DD toolkit. Adding state-specific trends asks: \"Did mortality deviate from each state's own trend when the MLDA changed?\" rather than \"Did mortality deviate from the national average?\" If the estimate survives this test, it provides strong evidence that the MLDA effect is not an artifact of differential pre-existing trends. This exercise connects directly to the conceptual discussion of parallel trends in the chapter.\n\n",
    "supporting": [
      "05-differences-in-differences_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}